### ISSUE TITLE
Can you point to a sample app of angular using polymer? 

### ISSUE THREAD

**Issue by chaoranxie** [angular/custom-elements-interop#3]
Can you point to a sample app of angular using polymer? Thanks

**Comment by hotforfeature** [comment]
I believe this repo is more focused on generic web components than anything Polymer-specific. There are two libraries out there (with samples) for Angular and Polymer specifically:

Angular 2.x and Polymer 1 - https://github.com/platosha/angular-polymer
Angular 4+ and Polymer 2 - https://github.com/hotforfeature/origami

**Comment by chaoranxie** [comment]
Thanks @hotforfeature closing this one
